### ISSUE TITLE
Readme needs round times, is confusing

### ISSUE THREAD

**Issue by juancarlospaco** [UNIcodeX/nimformat#2]
I linked the project to some people, they say is a lot slower, because of the `e-05` ending on the readme,
I think you should round the float, kinda format it more human readable, 
so people stops thinking this is slower than vanilla replace, is confusing. 
People thinks is 100 times slower.

like:
```
Nim    = 0.0007
Python = 1.75
```

**Comment by UNIcodeX** [comment]
That's confusing. I'm not sure what the point of doing this repo would be if it were 100x slower...
https://github.com/UNIcodeX/nimformat#times

**Comment by UNIcodeX** [comment]
Documenting that the times section on the README.md was updated. Closing issue.
